
SRCS=$(shell find -type f -name '*.lua')

../../../res/game/object_data/objects.dat: $(SRCS)
	./compile_object_data.sh ../../../res/game/object_data/objects.dat


clean:
	rm -f ../../../res/game/object_data/objects.dat



